name: movies_apirest_flutter
description: A movie wiki using ApiRest and BloC.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Api Rest: dio client generator, if something change, run: ` flutter pub run build_runner watch`.
  retrofit: ^3.0.1+1

  # State Management.
  flutter_bloc: ^7.0.1

  #Animations.
  animations: ^2.0.2

  #Utils.
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.18
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Api Rest: dio client generator.
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf
          weight: 400

  assets:
    - assets/icons/app_icon.png
    - assets/images/drawer.jpg
    - assets/images/camera_gray.png
